version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: airline_user
      POSTGRES_PASSWORD: airline_password
      POSTGRES_DB: airline_test_db
    ports:
      - "5433:5432"  # Changed from 5432:5432 to 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: